### ISSUE TITLE
Could you please provide the data corresponding to the figures of of experiments in the paper——PETS? Because we would like to like cite PETS as one of the state of the art work in our paper, but time is limited. Thank you![Feature Request]

### ISSUE THREAD

**Issue by ChengpengLi1003** [ByMic/PETS#1]

**Comment by michaelbayerle** [comment]
This is an unofficial implementation of PETS. For questions regarding the paper, please contact the original authors directly or open an issue in the official repo (https://github.com/kchua/handful-of-trials).
